* setup-local-tooling

** Assumed dependencies
At the moment I'm assuming jq is already installed and in your path.
On mac I assume you have homebrew, otherwise I assume you have either 'apt' or 'pacman'.  I may add something for yum or dnf or whatever people use these days for rpm in the future.  When I have more time I'll likely add something for windows (chocolatey or something maybe?)... or just use WSL2?

** Initial emacs setup

Running emacs bootstrapper will setup emacs packages I use, some dependencies (probably not all worked out just yet), download fonts I use, download the latest version of plantuml for use with emacs org-mode.  Setup dependencies for org-export of documents I commonly use for creating pdfs or similar exported docs from my notes and architectural documents.   I probably should throw rust-setup and cli setup in here too to make things a nice one-shot setup.

For now, bootstrap is ran like so:
#+BEGIN_SRC sh
./bootstrap_emacs.sh
#+END_SRC

Note: you can run this again to sync emacs config and elfeed.org file to your setup.  This way you can keep multiple computers in sync.  An emacs will popup if you already have ran this once with ediff to merge the changes manually through emerge.

** Font downloads

I'm currently pulling from latest github tag on nerdfonts, so if you want to use my bash function for installing fonts just realize that if there's a duplicate name it's going to break (which is why I use the full '.zip' to insure adds like InconsolataGo and InconsolataXYZ don't get in the way of Inconsolata on the filter.

** Dependencies

I'm currently testing everything but the debian deps as I'm building off that computer.  I'll update the others over time (likely to lag more on the mac side as I only use that for work and everythings setup).

If you start using this and want to make an improvement just send me a request and I'll be happy to let you throw a PR.


** TODO: Add rustup install

** TODO: Add rust cli tools:  ripgrep, bat, exa, etc.

** TODO: Add oh-my-zsh or starship

** TODO: Add aws serverless dependencies scripts


